config/routes.rb
UnderPantsGnomes::Application.routes.draw do

  resources :contacts

  resources :abouts
  
  post 'cart/cart', to: 'cart#cart', as: 'cart'
  get  'cart/cart', to: 'cart#index', as: 'cart_index'
  get  'cart/remove', to: 'cart#remove_from_cart', as: 'remove_item'
  post  'cart/remove', to: 'cart#remove_from_cart', as: 'remove_item1'
  get  'cart/logout', to: 'cart#logout', as: 'cart_logout'

  get "home/index"
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :orders

  resources :customers   

  resources :provinces

  resources :line_items

  resources :categories

  resources :products 
 
   
    

  
  
  get 'search' => 'home#search', as: 'search'
  get 'search_results' => 'home#search_results', as: 'search_results'
  
  

  root 'home#index'

end

app/models/about.rb
class About < ActiveRecord::Base
  validates_presence_of :title
  validates_presence_of :content
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :products
end

app/models/contact.rb
class Contact < ActiveRecord::Base
end

app/models/customer.rb
class Customer < ActiveRecord::Base
  belongs_to :province
  has_many   :orders
  validates_presence_of :name, :billing_address, :shipping_address, :postal_code, :city, :email_address
end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
  belongs_to :product
  belongs_to :order
end

app/models/order.rb
class Order < ActiveRecord::Base
  has_many :line_items
  belongs_to :customer
  has_many :products, :through => :line_items
end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :category
  has_many :line_items
  mount_uploader :image, ImageUploader
  validates_presence_of :name, :description, :price, :stock_quantity
  validates_uniqueness_of :name


  def self.keyword_search(keywords, option)
    keywords = "%" +  keywords + "%"
    if option === ""
      Product.where("name LIKE ? OR description LIKE ?",
                                    keywords, keywords)
    else
      Product.where("name LIKE ? AND category_id = ? OR description LIKE ? AND category_id = ? ",
                                    keywords, option, keywords, option)   
    end
    
      
  end
end

app/models/province.rb
class Province < ActiveRecord::Base
  has_many :customers
end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  before_action :set_products
  def index
    flash[:notice] = 'Welcome to the site!'
    @cart_items = session[:cart]
    @ids = session[:ids]
    @qtys = session[:qtys]
    @counter = 0
    
    if @ordered.nil?
      @ordered = []
    end
    
    @ids.each do |id|    
      @ordered << Product.find(id)
    end
   
    if session[:visit_count].nil?
      @visit_count = 1
    else
      @visit_count = session[:visit_count] + 1
    end
    
    session[:visit_count] = @visit_count
  end
  
  def cart
    
    if session[:cart].nil? && params[:product_id].present?
      session[:cart] = []
      session[:cart] << {params[:product_id] => params[:qty]}
      session[:ids]= []
      session[:ids] << params[:product_id]
      session[:qtys]= []
      session[:qtys] << params[:qty]
      load_cart
    else
      add_to_cart
      
    end
    
  end
  
  def load_cart
    
    
    redirect_to :action => :index

  end
  
  def add_to_cart
    session[:cart] << {params[:product_id] => params[:qty]}
    session[:ids] << params[:product_id]
    session[:qtys] << params[:qty]
    load_cart   
  end
  
  def remove_from_cart
    session[:cart].delete_at(params[flash[:product_remove_id]].to_i)
    load_cart
  end
  
  def logout
    session[:visit_count] = nil
  end
  
  private
    
    # Use callbacks to share common setup or constraints between actions.
    def set_products
      @products_ordered = Product.where("id = ?", params[:product_id])      
    end
end

app/controllers/provinces_controller.rb
class ProvincesController < ApplicationController
  before_action :set_province, only: [:show, :edit, :update, :destroy]

  # GET /provinces
  # GET /provinces.json
  def index
    @provinces = Province.all
  end

  # GET /provinces/1
  # GET /provinces/1.json
  def show
  end

  # GET /provinces/new
  def new
    @province = Province.new
  end

  # GET /provinces/1/edit
  def edit
  end

  # POST /provinces
  # POST /provinces.json
  def create
    @province = Province.new(province_params)

    respond_to do |format|
      if @province.save
        format.html { redirect_to @province, notice: 'Province was successfully created.' }
        format.json { render action: 'show', status: :created, location: @province }
      else
        format.html { render action: 'new' }
        format.json { render json: @province.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /provinces/1
  # PATCH/PUT /provinces/1.json
  def update
    respond_to do |format|
      if @province.update(province_params)
        format.html { redirect_to @province, notice: 'Province was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @province.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /provinces/1
  # DELETE /provinces/1.json
  def destroy
    @province.destroy
    respond_to do |format|
      format.html { redirect_to provinces_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_province
      @province = Province.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def province_params
      params.require(:province).permit(:name, :pst, :hst, :gst)
    end
end

app/helpers/abouts_helper.rb
module AboutsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/checkout_helper.rb
module CheckoutHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/provinces_helper.rb
module ProvincesHelper
end

app/views/provinces/_form.html.erb
<%= form_for(@province) do |f| %>
  <% if @province.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@province.errors.count, "error") %> prohibited this province from being saved:</h2>

      <ul>
      <% @province.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :pst %><br>
    <%= f.text_field :pst %>
  </div>
  <div class="field">
    <%= f.label :hst %><br>
    <%= f.text_field :hst %>
  </div>
  <div class="field">
    <%= f.label :gst %><br>
    <%= f.text_field :gst %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/provinces/index.html.erb
<h1>Listing provinces</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Pst</th>
      <th>Hst</th>
      <th>Gst</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @provinces.each do |province| %>
      <tr>
        <td><%= province.name %></td>
        <td><%= province.pst %></td>
        <td><%= province.hst %></td>
        <td><%= province.gst %></td>
        <td><%= link_to 'Show', province %></td>
        <td><%= link_to 'Edit', edit_province_path(province) %></td>
        <td><%= link_to 'Destroy', province, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Province', new_province_path %>

app/views/provinces/show.7.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @province.name %>
</p>

<p>
  <strong>Pst:</strong>
  <%= @province.pst %>
</p>

<p>
  <strong>Hst:</strong>
  <%= @province.hst %>
</p>

<p>
  <strong>Gst:</strong>
  <%= @province.gst %>
</p>

<%= link_to 'Edit', edit_province_path(@province) %> |
<%= link_to 'Back', provinces_path %>