config/routes.rb
UnderPantsGnomes::Application.routes.draw do

  resources :contacts

  resources :abouts
  
  post 'cart/cart', to: 'cart#cart', as: 'cart'
  get  'cart/cart', to: 'cart#index', as: 'cart_index'
  get  'cart/remove', to: 'cart#remove_from_cart', as: 'remove_item'
  post  'cart/remove', to: 'cart#remove_from_cart', as: 'remove_item1'
  get  'cart/logout', to: 'cart#logout', as: 'cart_logout'

  get "home/index"
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :orders

  resources :customers   

  resources :provinces

  resources :line_items

  resources :categories

  resources :products 
 
   
    

  
  
  get 'search' => 'home#search', as: 'search'
  get 'search_results' => 'home#search_results', as: 'search_results'
  
  

  root 'home#index'

end

app/models/about.rb
class About < ActiveRecord::Base
  validates_presence_of :title
  validates_presence_of :content
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :products
end

app/models/contact.rb
class Contact < ActiveRecord::Base
end

app/models/customer.rb
class Customer < ActiveRecord::Base
  belongs_to :province
  has_many   :orders
  validates_presence_of :name, :billing_address, :shipping_address, :postal_code, :city, :email_address
end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
  belongs_to :product
  belongs_to :order
end

app/models/order.rb
class Order < ActiveRecord::Base
  has_many :line_items
  belongs_to :customer
  has_many :products, :through => :line_items
end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :category
  has_many :line_items
  mount_uploader :image, ImageUploader
  validates_presence_of :name, :description, :price, :stock_quantity
  validates_uniqueness_of :name


  def self.keyword_search(keywords, option)
    keywords = "%" +  keywords + "%"
    if option === ""
      Product.where("name LIKE ? OR description LIKE ?",
                                    keywords, keywords)
    else
      Product.where("name LIKE ? AND category_id = ? OR description LIKE ? AND category_id = ? ",
                                    keywords, option, keywords, option)   
    end
    
      
  end
end

app/models/province.rb
class Province < ActiveRecord::Base
  has_many :customers
end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  before_action :set_products
  def index
    flash[:notice] = 'Welcome to the site!'
    @cart_items = session[:cart]
    @ids = session[:ids]
    @qtys = session[:qtys]
    @counter = 0
    
    if @ordered.nil?
      @ordered = []
    end
    
    @ids.each do |id|    
      @ordered << Product.find(id)
    end
   
    if session[:visit_count].nil?
      @visit_count = 1
    else
      @visit_count = session[:visit_count] + 1
    end
    
    session[:visit_count] = @visit_count
  end
  
  def cart
    
    if session[:cart].nil? && params[:product_id].present?
      session[:cart] = []
      session[:cart] << {params[:product_id] => params[:qty]}
      session[:ids]= []
      session[:ids] << params[:product_id]
      session[:qtys]= []
      session[:qtys] << params[:qty]
      load_cart
    else
      add_to_cart
      
    end
    
  end
  
  def load_cart
    
    
    redirect_to :action => :index

  end
  
  def add_to_cart
    session[:cart] << {params[:product_id] => params[:qty]}
    session[:ids] << params[:product_id]
    session[:qtys] << params[:qty]
    load_cart   
  end
  
  def remove_from_cart
    session[:cart].delete_at(params[flash[:product_remove_id]].to_i)
    load_cart
  end
  
  def logout
    session[:visit_count] = nil
  end
  
  private
    
    # Use callbacks to share common setup or constraints between actions.
    def set_products
      @products_ordered = Product.where("id = ?", params[:product_id])      
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
    
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render action: 'show', status: :created, location: @product }
      else
        format.html { render action: 'new' }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :description, :price, :stock_quantity, :category_id, :image)
    end
end

app/helpers/abouts_helper.rb
module AboutsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/checkout_helper.rb
module CheckoutHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/provinces_helper.rb
module ProvincesHelper
end

app/views/products/_cartproduct.html.haml
%section.item
  %p.image= link_to image_tag(product.image), product
  %p= link_to product.name, product
  %p.description= product.description
  %p.category
    -if product.category.present?
      =link_to "#{product.category.name}", product.category
    -else
      = "None."
  %p= "Price: #{number_to_currency(product.price)}"
  %p= "In Stock: #{product.stock_quantity}"
  %section{id: "add_to_cart"}
    =form_tag cart_path method: 'post' do
      =text_field_tag :qty
      %input{type: "hidden", name: "product_id", value: product.id}
      =submit_tag "Add to Cart"

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :image_name %><br>
    <%= f.text_field :image_name %>
  </div>
  <div class="field">
    <%= f.label :stock_quantity %><br>
    <%= f.text_field :stock_quantity %>
  </div>
  <div class="field">
    <%= f.label :category_id_id %><br>
    <%= f.text_field :category_id_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/_product.html.haml
%section.item
  %p.image= link_to image_tag(product.image), product
  %p= link_to product.name, product
  %p.description= product.description
  %p.category
    -if product.category.present?
      =link_to "#{product.category.name}", product.category
    -else
      = "None."
  %p= "Price: #{number_to_currency(product.price)}"
  %p= "In Stock: #{product.stock_quantity}"
  %section{id: "add_to_cart"}
    =form_tag "cart/cart", method: 'post' do
      =text_field_tag :qty
      %input{type: "hidden", name: "product_id", value: product.id}
      =submit_tag "Add to Cart"

app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.haml
%h1 Welcome

%section= render partial: "product", collection: @products

app/views/products/new.html.erb
<h1>New product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.haml
%p#notice= notice
%p
  %strong Name:
  = @product.name
%p
  %strong Description:
  = @product.description
%p
  %strong Price:
  = @product.price
%p
  %strong Image name:
  = @product.image
%p
  %strong Stock quantity:
  = @product.stock_quantity
%p
  %strong Category:
  = @product.category_id
= link_to 'Edit', edit_product_path(@product)
|
\#{link_to 'Back', products_path}