config/routes.rb
UnderPantsGnomes::Application.routes.draw do

  resources :contacts

  resources :abouts
  
  post 'cart/cart', to: 'cart#cart', as: 'cart'
  get  'cart/cart', to: 'cart#index', as: 'cart_index'
  get  'cart/remove', to: 'cart#remove_from_cart', as: 'remove_item'
  post  'cart/remove', to: 'cart#remove_from_cart', as: 'remove_item1'
  get  'cart/logout', to: 'cart#logout', as: 'cart_logout'

  get "home/index"
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :orders

  resources :customers   

  resources :provinces

  resources :line_items

  resources :categories

  resources :products 
 
   
    

  
  
  get 'search' => 'home#search', as: 'search'
  get 'search_results' => 'home#search_results', as: 'search_results'
  
  

  root 'home#index'

end

app/models/about.rb
class About < ActiveRecord::Base
  validates_presence_of :title
  validates_presence_of :content
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :products
end

app/models/contact.rb
class Contact < ActiveRecord::Base
end

app/models/customer.rb
class Customer < ActiveRecord::Base
  belongs_to :province
  has_many   :orders
  validates_presence_of :name, :billing_address, :shipping_address, :postal_code, :city, :email_address
end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
  belongs_to :product
  belongs_to :order
end

app/models/order.rb
class Order < ActiveRecord::Base
  has_many :line_items
  belongs_to :customer
  has_many :products, :through => :line_items
end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :category
  has_many :line_items
  mount_uploader :image, ImageUploader
  validates_presence_of :name, :description, :price, :stock_quantity
  validates_uniqueness_of :name


  def self.keyword_search(keywords, option)
    keywords = "%" +  keywords + "%"
    if option === ""
      Product.where("name LIKE ? OR description LIKE ?",
                                    keywords, keywords)
    else
      Product.where("name LIKE ? AND category_id = ? OR description LIKE ? AND category_id = ? ",
                                    keywords, option, keywords, option)   
    end
    
      
  end
end

app/models/province.rb
class Province < ActiveRecord::Base
  has_many :customers
end

app/helpers/abouts_helper.rb
module AboutsHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/checkout_helper.rb
module CheckoutHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/provinces_helper.rb
module ProvincesHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title The Underpants Gnomes Used Underpants Emporium!
    = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags
  %body
    %section{:id => "container"}
      %header
        #logo
          = link_to image_tag("logo.png"), "/"
        %h1{:id => "header_line"}= link_to "Underpants Gnome's ", "/"
        %h1{:id => "header_line2"}= link_to "Used Underpants Emporium", "/"
        %nav
          %ul
            %li
              = link_to "Home", root_path 
            %li
              = link_to "Products", products_path
            %li
              = link_to "About Us", abouts_path
            %li
              = link_to "Contact Us", contacts_path
            %li{:id => "search"}
              = form_tag search_results_path, method: 'get' do
                = text_field_tag :search_keywords
                = submit_tag "Search"
                = select_tag :option, options_from_collection_for_select(@categories, "id", "name"),
                              :prompt => "All Products"
                
        %section.clearfix       
      %section{:id => "maincontent"}
        %section{:id => "sidebar_nav"}= render :partial => "categories/sidebarnav"
          
          
        %section{:id => "content"}= yield
        %section.clearfix
      %footer
        %nav
          %ul
            %li
              = link_to "Home", "/"
            %li
              = link_to "Products", "/products"
            %li
              = link_to "About Us", "/abouts"
            %li
              = link_to "Contact Us", "/contacts"
        %h5 &copy;opyWrong Underpants Gnome's Used Underpants Emporium
        %section.clearfix
        
    

  
    